### ISSUE TITLE
How do I recover my ssh key?

### ISSUE THREAD

**Issue by robodruid** [Low-Frequency/klipper_backup_script#16]
Screwed up and forgot the ssh key. How do I recover it?

**Comment by Low-Frequency** [comment]
Hi
The keys are saved in `~/.ssh`.
To get the public key for GitHub you can simply do `cat ~/.ssh/id_rsa.pub`

**Comment by robodruid** [comment]
Oh I just deleted everything and started again. I now get this error:
![image](https://user-images.githubusercontent.com/89250364/227194962-9757643f-35ee-4d2f-b846-729ba2779035.png)

**Comment by Low-Frequency** [comment]
The install script moves some files around. That's why it can't be executed a second time without downloading the files again from the repository.
After you uninstall the script, but still have the script folder set up, you have to do a `git -C ~/scripts/klipper_backup_script pull` before installing it again. I might change that behaviour to copy the files instead of moving them.

**Comment by robodruid** [comment]
Ok. I'll try when I get home and let you know

**Comment by robodruid** [comment]
![image](https://user-images.githubusercontent.com/89250364/227732596-8986ddea-86fa-4807-89ff-c295fadca2c4.png)
Ok. It seems to have been successfully installed, but none of the commands work, and the config file doesn't show my time schedule I set up

**Comment by Low-Frequency** [comment]
Seems like you ran into one of the safety checks the script does to not break the config after it already has been written.
The config for the script is generated in three steps:
1. The config template gets moved from the repository folder to `$HOME/.config/klipper_backup_script/backup.cfg`
2. The existing options in the template get replaced
3. The optional options get added at the end

It seems that the first step somehow failed. It can't be permission related since the script added the optional configs that should be at the end of the file. I can only think of one possible scenario to explain the behaviour.
Did it give you an error message like this?
```bash
mv: cannot stat '/home/mainsail/scripts/klipper_backup_script/backup.cfg': no such file or directory
```
A missing config template is the only way I can think of how that might have happened since the file will be created in step 3 if it doesn't exist and it will definitely look like your file. However it looks like that 

Maybe starting from a completely blank state is the best way to solve this:
```bash
sudo systemctl disable gitbackup.service
sudo rm /etc/systemd/system/gitbackup.service
sudo rm /usr/local/bin/backup
sudo rm /usr/local/bin/restore
sudo rm /usr/local/bin/uninstall_bak_util
rm -r ~/.config/klipper_backup_script
rm -r ~/scripts/klipper_backup_script
mkdir -p ~/scripts/klipper_backup_script
git clone https://github.com/Low-Frequency/klipper_backup_script.git ~/scripts/klipper_backup_script
cd ~/scripts/klipper_backup_script
chmod +x setup_klipper_backup.sh
./setup_klipper_backup.sh
```

This should remove all components of the script and start a completely fresh install. Some of the commands might fail since the install script failed, but better try to remove things that don't exist than leaving some broken files behind.
Before you execute those command though you'll have to delete the `.git` folder in your klipper config folder. Otherwise the initial setup of the git repo inside that folder will fail.

If that doesn't solve the problem I can offer you a troubleshooting session via Discord. I'll try to be online a little more frequent on there :sweat_smile:

**Comment by Low-Frequency** [comment]
Since I haven't heared back from you I assume everything is working. If not check out the new version I just released. It's definitely easier to set up.

If you still have trouble with the script plaese let me know, so I can investigate further.
