### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by EpiXSim0n** [Low-Frequency/klipper_backup_script#25]
After install i tried my first Backup but i get this error:
`##### Choose action: 4
tee: /home/pi/kgb-log/kgb-2023-11-18.log: No such file or directory
[2023-11-18 10:27:20]: Backing /home/pi/klipper_config up to GitHub
tee: /home/pi/kgb-log/kgb-2023-11-18.log: No such file or directory
[2023-11-18 10:27:20]: Adding changes to push
fatal: not a git repository (or any of the parent directories): .git
tee: /home/pi/kgb-log/2023-11-18.log: No such file or directory
tee: /home/pi/kgb-log/kgb-2023-11-18.log: No such file or directory
[2023-11-18 10:27:20]: Committing to GitHub repository
tee: /home/pi/kgb-log/2023-11-18.log: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
tee: /home/pi/kgb-log/kgb-2023-11-18.log: No such file or directory
[2023-11-18 10:27:20]: Pushing to GitHub repository
fatal: not a git repository (or any of the parent directories): .git
tee: /home/pi/kgb-log/2023-11-18.log: No such file or directory
tee: /home/pi/kgb-log/kgb-2023-11-18.log: No such file or directory
[2023-11-18 10:27:20]: /home/pi/klipper_config backup failed
tee: /home/pi/kgb-log/kgb-2023-11-18.log: No such file or directory
[2023-11-18 10:27:20]: Deleting old logs
find: ‘/home/pi/kgb-log’: No such file or directory
   [⚠] Backup failed! Please check the log
`

My config files looks like this:

`GIT="1"
GITHUB_USER="EpiXSim0n"
GITHUB_MAIL="simon********@gmail.com"
GITHUB_BRANCH="main"
REPO_LIST=(https://github.com/EpiXSim0n/Voron24)
CONFIG_FOLDER_LIST=(/home/pi/klipper_config)
LOG_ROTATION="1"
LOG_RETENTION="3"
SCHEDULED_BACKUPS="0"
BACKUP_INTERVAL="7"
TIME_UNIT="d"
`
I dont see anything wrong here.
Help pls.

**Comment by EpiXSim0n** [comment]
After creating folder kgb-log i get this error:
`
[2023-11-18 10:54:04]: Backing /home/pi/klipper_config up to GitHub
[2023-11-18 10:54:04]: Adding changes to push
fatal: not a git repository (or any of the parent directories): .git
[2023-11-18 10:54:04]: Committing to GitHub repository
fatal: not a git repository (or any of the parent directories): .git
[2023-11-18 10:54:04]: Pushing to GitHub repository
fatal: not a git repository (or any of the parent directories): .git
[2023-11-18 10:54:04]: /home/pi/klipper_config backed up
[2023-11-18 10:54:04]: Deleting old logs
`

**Comment by Low-Frequency** [comment]
Did you have to create the `kgb-log` folder manually?

**Comment by UnnamedDave** [comment]
> Did you have to create the `kgb-log` folder manually?

I had this issue as well, and yes. I had to create it manually to get things working.

**Comment by Low-Frequency** [comment]
The only way I can see this happen is if the script was installed as root, but the config folders are located in a different home directory. The `kgb-log` folder is created on install. [See here](https://github.com/Low-Frequency/Klipper-Git-Backup/blob/main/lib/functions/install_functions.sh#L175)

In this case: install it as the user which is running klipper (Usually the user you login with).

Also in this step the config folders get initialized as git repos. In the error message @EpiXSim0n posted it clearly says that the config folder isn't a git repo, which lets me believe, that the install step wasn't executed.

I might implement a warning message if the script was set up, but not installed to at least notify users that the script won't work properly in this state. Might take a while however since I'm pretty busy lately and don't do much IT related stuff in my free time anymore.

**Comment by UnnamedDave** [comment]
>  that the install step wasn't executed.

Yes, I had to manually configure my github info as well. So the setup step was obviously not executed. Running `systemctl list-timers kgb` also provides a 0 timers listed message so something got a bit funky. Ill do some messing around and see if I can figure out where its going wrong.

**Comment by Low-Frequency** [comment]
If you run the install step the script will do all the configuration necessary. It doesn't matter if you already initialized the git repo. It will just prompt you that it already is a git repo and skip this step, so you should be able to run it to fix the errors you got.

**Comment by Low-Frequency** [comment]
I had to fix some scripts I wrote for me personally today and I just took the additional time to catch up to the improvements on this project. The new version checks if the script was successfully installed on quitting the installer. Makes quitting the installer without installing the script a bit more annoying, but it's better than errors on backups I guess.

I'll close this issue now since the source of the errors has been identified and the fix is also documented.
