### ISSUE TITLE
Problem after reinstalling 

### ISSUE THREAD

**Issue by varazir** [Low-Frequency/klipper_backup_script#26]
Hi, 

I bought a new raspberry pie ( used BTT CB1 before) and needed to reinstall. 
I installed this plugin and set it up to point to the old repo but I keep getting error. 

[2024-03-16 17:05:41]: Backing /home/pi/printer_data up to Git
[2024-03-16 17:05:41]: Adding changes to push
[2024-03-16 17:05:41]: Committing to Git repository
[main 3a1ee41] backup 2024-03-16 17:05:41
 4 files changed, 990 insertions(+)
[2024-03-16 17:05:41]: Pushing to Git repository
To github.com:varazir/KlipperWanhaoBackup.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:varazir/KlipperWanhaoBackup.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[2024-03-16 17:05:43]: /home/pi/printer_data backed up
[2024-03-16 17:05:43]: Deleting old logs
   [➔] Backup succeeded 

How should I go forward with this ?

**Comment by Low-Frequency** [comment]
Hi,

did you set the script up with the standard install? If so I guess you had the config folder and the script assumed it was a new repo. This is by design, since I didn't had the scenario in mind that one might reinstall and fetch the repo instead of creating a new one. I guess that would be a good addition to the script. I'll see what I can do if I find time between my private projects.

In the meantime you could rename the existing config folder, so the script and klipper don't see it anymore and clone your existing repo in that place:
```
mv /path/to/config/folder /path/to/config/folder.bak
mkdir /path/to/config/folder
git clone git@github.com:varazir/<reponame>.git /path/to/config/folder
```

This way the script should still be functional, you'll retain all of your configs and can manually merge them if needed.

**Comment by varazir** [comment]
> Hi,
> 
> did you set the script up with the standard install? If so I guess you had the config folder and the script assumed it was a new repo. This is by design, since I didn't had the scenario in mind that one might reinstall and fetch the repo instead of creating a new one. I guess that would be a good addition to the script. I'll see what I can do if I find time between my private projects.
> 
> In the meantime you could rename the existing config folder, so the script and klipper don't see it anymore and clone your existing repo in that place:
> 
> ```
> mv /path/to/config/folder /path/to/config/folder.bak
> mkdir /path/to/config/folder
> git clone git@github.com:varazir/<reponame>.git /path/to/config/folder
> ```
> 
> This way the script should still be functional, you'll retain all of your configs and can manually merge them if needed.

The scenario is if you need to reinstall your RPi you use the scrip to restore all settings from a old repo.

**Comment by 5teveO** [comment]
Being a bit of a numpty at these kind of things - and certainly not technical - I have now re-installed klipper twice now on 2 different machines. I would find it very helpful to have it restore to a different machine or even smae machine new install (after all sd cards go bad regularly) I'm sure it can be done manually with some git magic.. but unfortunately I'm mechanically good.. and software.. well.. bad doesnt leave room for worse.. which is what i am!

My current method of restoration.. is copy the files from git - add them to klipper - delete or rename the old repository, and recreate a new repository, then reinstall KGB and set it up.. Its easy to do.. but it would be awesome to connect it to an old repository and bring that back over to the new installation

By the way - Great creation.. i use it on both my machines and it runs every 12 hours... just like clockwork. Really appreciate you making this.

Steve O

**Comment by Low-Frequency** [comment]
I'm sorry that I haven't replied to issues in quite some time. The reason for that is a change in interests. My free time activities shifted from 3D printing to managing my own servers and developing my skills as a system administrator and DevOPS engineer.

While I'm still passionate about developing useful scripts, I kind of lost interest in this side project due to the sheer amount of work I put into my servers and the satisfaction I got out of it. However it might be the time to get back into old habits (and old code) and tackle the open issues for this project.

I'll try to set up a development and testing environment over the next few days to be able to iron out some bugs and redevelop the restore process to be more useful. It might take me some time to get back into it, since I basically have no idea what I did anymore and the script evolved to be more complex than I initially intended, but I fully intend to invest some time into this project again over the next few weeks.

**Comment by Low-Frequency** [comment]
I spent about 12 hours reading, refactoring and documenting the code over the last two days (This thing is way bigger than I remember :laughing:). So far I only found a few minor issues with input validation and some functions which needed some optimization. However the restore process is a mess considering new installations exist... Apparently I did not think of that... This definitely needs a complete rework.

I made a rough plan to streamline the whole backup and restore process:
1. Local backup folder for all instances
2. Only one git repo for all instances. Local backup folder will be pushed to git
3. Restore will have a switch for local restore or git restore
    * Git Restore will first pull the repo to a new location and then overwrite the existing config
    * Local restore will just move some files around
4. Setup will be a bit easier
    * Auto detect `printer_data` folders in the home directory of the user
    * User will still be able to override the auto detected folders
 
This will cause previous installations to not work after the update if the new version is used. Therefore I'll need to think of a process to migrate. Maybe change some config keys, check for them when the script runs and automatically start a migration wizard, or something like that.

**Comment by 5teveO** [comment]
> I spent about 12 hours reading, refactoring and documenting the code over the last two days (This thing is way bigger than I remember 😆). So far I only found a few minor issues with input validation and some functions which needed some optimization. However the restore process is a mess considering new installations exist... Apparently I did not think of that... This definitely needs a complete rework.
> 
> I made a rough plan to streamline the whole backup and restore process:
> 
> 1. Local backup folder for all instances
> 2. Only one git repo for all instances. Local backup folder will be pushed to git
> 3. Restore will have a switch for local restore or git restore
>    
>    * Git Restore will first pull the repo to a new location and then overwrite the existing config
>    * Local restore will just move some files around
> 4. Setup will be a bit easier
>    
>    * Auto detect `printer_data` folders in the home directory of the user
>    * User will still be able to override the auto detected folders
> 
> This will cause previous installations to not work after the update if the new version is used. Therefore I'll need to think of a process to migrate. Maybe change some config keys, check for them when the script runs and automatically start a migration wizard, or something like that.

I'm fairly useless at this kind of thing - so take my comments with a pinch of salt - I appreciate the software you produced and even more so you starting to look at it again!

1 - I assume you mean all printer instances? (how will this be presented in the local folder? - individual folders for the instances?)
2 - Cant see a problem with this - I assume any subfolders - eg instances will be pushed too.
3 - sounds ideal - although i'm trying to think of a scenario of when a local restor would be used? I guess the user can copy the back up folder to a local machine and then copy it back on system reinstall? In my instance I've just needed the backup when an sd card has crapped itself or moving hosts (eg 3b to 5 pi) so havent had the use of a local restore
4 - I'm not great at linux but i didnt struggle too much with the installation - maybe just more complete documentation (written for dummies like me) as i find a lot of linux programs like this have instructions written like you know what to do - Very common i have found in 3d printing 

Again appreciate your efforts and revisiting it.

Steve

**Comment by Low-Frequency** [comment]
Feedback is always welcome, especially when developing. When you code something, you have a very different view than a user. It's almost as wearing blinders, so it's nice if someone shines some light on the issues I may be overlooking and questiones the things I do.

Concerning local backups:
Its basically just a folder containing a copy of the current config. I do this to be able to only use one git repo for all instances. It's easier for the user and also makes the logic needed to do the backup way easier. It might make the logic for selecting backups a bit trickier, but I'll figure out a way to make it easy for the user. However this really simplifies the restore process since it's basically just a `git clone` and then copy the selected backup.
Another plus for the local backup is that you can super quickly restore a config. Either manually by copying it, or let the script do that. The local backup and the repo will basically be mirrored. But in the end the local restore will be an option just because the structure makes it possible, so why not implement it?

As for the structure, it will look something like this:
```
/home/pi/
  |_ kgb-data
      |_ backups
          |_ printer1_data
          |    |_ config
          |_ printer2_data
               |_ config
```

This way all instances will be cleanly separated.

The backups folder will be the repo, so on GitHub all you will see are the instance folders and the config folders inside of each one.

As for the documentation:
As a technical person it's kind of hard to document things in a non technical way, but I can certainly try. What would be some improvements you can think of? Maybe a more detailed explanation of the different menus and what the function of all config parameters are? Built in to the script as a default operation in all menus to explain the current menu, or would some documentation in the docs folder suffice?


To give an update on what has happend in the last day:
I reworked the backup and install functions. This means in the current state, only one repo is used for backups. This backup functionality is mirrored in the install, which will by default make the first backup. However there's no need to manually create the repo anymore. Also the SSH key will be added to the GitHub account automatically. But there's a small catch... This imposes the necessity to create an access token first, but I'll make sure to document how this is done in detail.
A big plus for doing it this way is that you can now configure an already existing repo and the script should detect that there is a backup present which can be restored during install.

The current to do:
1. Rework the restore process to finally be fully functional and use the new restore methods
2. Test the new functionality
3. Develop some functions to migrate old configs to v2

And as a small heads up:
Development will slow down a bit from now, since I won't have as much free time as in the last few days.

**Comment by 5teveO** [comment]
> Feedback is always welcome, especially when developing. When you code something, you have a very different view than a user. It's almost as wearing blinders, so it's nice if someone shines some light on the issues I may be overlooking and questiones the things I do.
> 
> Concerning local backups: Its basically just a folder containing a copy of the current config. I do this to be able to only use one git repo for all instances. It's easier for the user and also makes the logic needed to do the backup way easier. It might make the logic for selecting backups a bit trickier, but I'll figure out a way to make it easy for the user. However this really simplifies the restore process since it's basically just a `git clone` and then copy the selected backup. Another plus for the local backup is that you can super quickly restore a config. Either manually by copying it, or let the script do that. The local backup and the repo will basically be mirrored. But in the end the local restore will be an option just because the structure makes it possible, so why not implement it?
> 
> As for the structure, it will look something like this:
> 
> ```
> /home/pi/
>   |_ kgb-data
>       |_ backups
>           |_ printer1_data
>           |    |_ config
>           |_ printer2_data
>                |_ config
> ```
> 
> This way all instances will be cleanly separated.
> 
> The backups folder will be the repo, so on GitHub all you will see are the instance folders and the config folders inside of each one.
> 
> As for the documentation: As a technical person it's kind of hard to document things in a non technical way, but I can certainly try. What would be some improvements you can think of? Maybe a more detailed explanation of the different menus and what the function of all config parameters are? Built in to the script as a default operation in all menus to explain the current menu, or would some documentation in the docs folder suffice?
> 
> To give an update on what has happend in the last day: I reworked the backup and install functions. This means in the current state, only one repo is used for backups. This backup functionality is mirrored in the install, which will by default make the first backup. However there's no need to manually create the repo anymore. Also the SSH key will be added to the GitHub account automatically. But there's a small catch... This imposes the necessity to create an access token first, but I'll make sure to document how this is done in detail. A big plus for doing it this way is that you can now configure an already existing repo and the script should detect that there is a backup present which can be restored during install.
> 
> The current to do:
> 
> 1. Rework the restore process to finally be fully functional and use the new restore methods
> 2. Test the new functionality
> 3. Develop some functions to migrate old configs to v2
> 
> And as a small heads up: Development will slow down a bit from now, since I won't have as much free time as in the last few days.

You are welcome on the feedback - in my opinion everyone should be using this program on their klipper systems.. once set up its save me screwing things up a few times (mainly due to being able to see the old config etc) :)

Yep the local backup is understood and can see why you would do that - I guess its in the instance that the active config has been messed with and needs restoration. Most of my desperate restores have been from catastrophic card failure or similar so you would then fall back to remote restore.. the way you have it looks ideal from how I understand things.

Documentation wise - yes as a mechanical design engineer I understand the dilemma - you sit so close to the project its hard not to write it as though you know things.. 

in my honest opinion and i think this would go for a lot of users.. Klipper forces us into using linux - something I am very unfamiliar with and can do nothing on unless i have google constantly searching - even though i hail from the era of DOS. So for me a lot of things I need to do for klipper or touch using klipper puts me in to unfamiliar territory and can be quite intimidating. I managed to follow your instructions with a bit of headscratching so they are certainly not bad. however I find a full hand holding guide - step by step with commands and images where possible is generally what I need to complete things correctly and confidently. From what I see on klipper discord a lot of users are even less competant than myself (who I consider to be very incompetant with this stuff) so I think they get a put off very quickly unless its step by step.

Impressive update from what you say - and just in a day? i can barely get my socks on in a day :D I look forward to seeing it develop further and seeing what goodies you have for us... however please dont worry about development slowing - you are using YOUR time for FREE to develop software for us far less skilled that cannot do it ourselves! I appreciate it when anything happens ...

Steve

**Comment by Low-Frequency** [comment]
Thanks for the kind words. I'ts nice to hear that my work is valued. I tend to push myself to the limit in almost all situations  (especially when it comes to IT) due to the ability to hyperfocus on tasks. It's a blessing to be able to do this, but also a curse :laugh:

To put the development status in perspective:
I had two full days of free time which I dedicated to relearning what I did, commenting the code for future reference and further developing it, so quick progress was foreseeable. Also Bash is my weapon of choice when it comes to developing scripts since about 4 years now. I'm by no means an expert (I still consider myself a beginner since there's still an endless list of things to learn), but I always found a way to make it work. Nowadays I almost exclusively use it to get and manipulate data through APIs or automate pretty simple, but repetitive work, so it's nice to tinker with  something that needs interaction again.

I'll definitely keep your feedback in mind and will try my best to make the documentation as complete as possible. The main README will still be just a quick overview to get started as it should be, but I'll link further in depth documentation for configuring the script. This will be quite some extra work, but I think this will be worth the effort in the end.

**Comment by Low-Frequency** [comment]
Short update on the progress

I'm in the testing phase now. I've managed to iron out all the UI bugs that worked their way into the code while changing around some things. Also configuring the script seems to work fine. As a bonus I've started to implement a quick help into the installer.

Next step is to tackle some new bugs in the new functions of the install process. After that's done it's time to test the backup and restore process. When that works as expected it's time to document everything and release the new version.

And a small fun fact:
The current public version has 1533 lines of code. My development version currently almost doubled that with 2937 lines :laughing:

**Comment by Low-Frequency** [comment]
Another update on the progress

The backup and restore functions are now almost fully tested. The only thing that remains to be tested is the initial restore in the installation and the config migration function. Somehow a new UI bug managed to find it's way into the code, but that's just a minor optical deficiency (some of the spacings are off and I don't know why yet), which I will fix when the functional part is all sorted out.

Next week will be pretty busy for me, so I don't know if I'll be able to release the new version before my vacation in August, but I'll do my best to make it happen.

**Comment by 5teveO** [comment]
> Another update on the progress
> 
> The backup and restore functions are now almost fully tested. The only thing that remains to be tested is the initial restore in the installation and the config migration function. Somehow a new UI bug managed to find it's way into the code, but that's just a minor optical deficiency (some of the spacings are off and I don't know why yet), which I will fix when the functional part is all sorted out.
> 
> Next week will be pretty busy for me, so I don't know if I'll be able to release the new version before my vacation in August, but I'll do my best to make it happen.

well you certainly make some progress :) - sounds like a great update and i shall look forward to updating / testing etc.. I have a new machine that this will be perfect to try on. If you dont make any progress before your vacation - enjoy... and dont stress... current version is ticking along for me backing up... so i dont plan any restores any time soon :)

**Comment by Low-Frequency** [comment]
Thanks, I'll definitely enjoy my vacation :smile: 

And I have good news!

The only function that remains to be tested is the config migration from v1 to v2. After that it's only documentation, which will be a pretty big timesink. I might release the script without full documentation and add to it later since a new feature came to my mind while testing and I know I can't just document without tinkering with the code on the side :laughing: 
However the quick help in the menus is implemented and the basic setup guide is fully documented (including pictures).

The new feature that came to mind is removing instances from the backup. Right now you basically have to start over when you have a typo in the config, unless you modify it manually in the config. It's kind of unnecessary due to the auto detection of the printer_data directories, but it might be nice to have the option.

**Comment by Low-Frequency** [comment]
I have great news :partying_face: 

Version 2.0.0 is finally released. Testing the config migration went way smoother than expected and also the documentation wasn't as time consuming as I thought.

Feel free to leave feedback on the new version :smile:
